// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: engine/gameobject/proto/gameobject/lua_ddf.proto

package com.dynamo.lua.proto;

public final class Lua {
  private Lua() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LuaModuleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dmLuaDDF.LuaModule)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * For now provide both script and bytecode to support the engine build option
     * of compiling with vanilla lua.
     * </pre>
     *
     * <code>required .dmLuaDDF.LuaSource source = 1;</code>
     * @return Whether the source field is set.
     */
    boolean hasSource();
    /**
     * <pre>
     * For now provide both script and bytecode to support the engine build option
     * of compiling with vanilla lua.
     * </pre>
     *
     * <code>required .dmLuaDDF.LuaSource source = 1;</code>
     * @return The source.
     */
    com.dynamo.script.proto.Lua.LuaSource getSource();
    /**
     * <pre>
     * For now provide both script and bytecode to support the engine build option
     * of compiling with vanilla lua.
     * </pre>
     *
     * <code>required .dmLuaDDF.LuaSource source = 1;</code>
     */
    com.dynamo.script.proto.Lua.LuaSourceOrBuilder getSourceOrBuilder();

    /**
     * <pre>
     * NOTE: The following arrays must be equal in size
     * </pre>
     *
     * <code>repeated string modules = 2;</code>
     * @return A list containing the modules.
     */
    java.util.List<java.lang.String>
        getModulesList();
    /**
     * <pre>
     * NOTE: The following arrays must be equal in size
     * </pre>
     *
     * <code>repeated string modules = 2;</code>
     * @return The count of modules.
     */
    int getModulesCount();
    /**
     * <pre>
     * NOTE: The following arrays must be equal in size
     * </pre>
     *
     * <code>repeated string modules = 2;</code>
     * @param index The index of the element to return.
     * @return The modules at the given index.
     */
    java.lang.String getModules(int index);
    /**
     * <pre>
     * NOTE: The following arrays must be equal in size
     * </pre>
     *
     * <code>repeated string modules = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the modules at the given index.
     */
    com.google.protobuf.ByteString
        getModulesBytes(int index);

    /**
     * <pre>
     * required resources. same as modules but on the form /x/y/z.luac instead of x.y.z
     * </pre>
     *
     * <code>repeated string resources = 3 [(.resource) = true];</code>
     * @return A list containing the resources.
     */
    java.util.List<java.lang.String>
        getResourcesList();
    /**
     * <pre>
     * required resources. same as modules but on the form /x/y/z.luac instead of x.y.z
     * </pre>
     *
     * <code>repeated string resources = 3 [(.resource) = true];</code>
     * @return The count of resources.
     */
    int getResourcesCount();
    /**
     * <pre>
     * required resources. same as modules but on the form /x/y/z.luac instead of x.y.z
     * </pre>
     *
     * <code>repeated string resources = 3 [(.resource) = true];</code>
     * @param index The index of the element to return.
     * @return The resources at the given index.
     */
    java.lang.String getResources(int index);
    /**
     * <pre>
     * required resources. same as modules but on the form /x/y/z.luac instead of x.y.z
     * </pre>
     *
     * <code>repeated string resources = 3 [(.resource) = true];</code>
     * @param index The index of the value to return.
     * @return The bytes of the resources at the given index.
     */
    com.google.protobuf.ByteString
        getResourcesBytes(int index);

    /**
     * <code>optional .dmPropertiesDDF.PropertyDeclarations properties = 4;</code>
     * @return Whether the properties field is set.
     */
    boolean hasProperties();
    /**
     * <code>optional .dmPropertiesDDF.PropertyDeclarations properties = 4;</code>
     * @return The properties.
     */
    com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations getProperties();
    /**
     * <code>optional .dmPropertiesDDF.PropertyDeclarations properties = 4;</code>
     */
    com.dynamo.properties.proto.PropertiesProto.PropertyDeclarationsOrBuilder getPropertiesOrBuilder();

    /**
     * <code>repeated string property_resources = 5 [(.resource) = true];</code>
     * @return A list containing the propertyResources.
     */
    java.util.List<java.lang.String>
        getPropertyResourcesList();
    /**
     * <code>repeated string property_resources = 5 [(.resource) = true];</code>
     * @return The count of propertyResources.
     */
    int getPropertyResourcesCount();
    /**
     * <code>repeated string property_resources = 5 [(.resource) = true];</code>
     * @param index The index of the element to return.
     * @return The propertyResources at the given index.
     */
    java.lang.String getPropertyResources(int index);
    /**
     * <code>repeated string property_resources = 5 [(.resource) = true];</code>
     * @param index The index of the value to return.
     * @return The bytes of the propertyResources at the given index.
     */
    com.google.protobuf.ByteString
        getPropertyResourcesBytes(int index);
  }
  /**
   * Protobuf type {@code dmLuaDDF.LuaModule}
   */
  public static final class LuaModule extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dmLuaDDF.LuaModule)
      LuaModuleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LuaModule.newBuilder() to construct.
    private LuaModule(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LuaModule() {
      modules_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      resources_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      propertyResources_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LuaModule();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LuaModule(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.dynamo.script.proto.Lua.LuaSource.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = source_.toBuilder();
              }
              source_ = input.readMessage(com.dynamo.script.proto.Lua.LuaSource.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(source_);
                source_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                modules_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              modules_.add(bs);
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                resources_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              resources_.add(bs);
              break;
            }
            case 34: {
              com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = properties_.toBuilder();
              }
              properties_ = input.readMessage(com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(properties_);
                properties_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) != 0)) {
                propertyResources_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              propertyResources_.add(bs);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          modules_ = modules_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          resources_ = resources_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000010) != 0)) {
          propertyResources_ = propertyResources_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dynamo.lua.proto.Lua.internal_static_dmLuaDDF_LuaModule_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dynamo.lua.proto.Lua.internal_static_dmLuaDDF_LuaModule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dynamo.lua.proto.Lua.LuaModule.class, com.dynamo.lua.proto.Lua.LuaModule.Builder.class);
    }

    private int bitField0_;
    public static final int SOURCE_FIELD_NUMBER = 1;
    private com.dynamo.script.proto.Lua.LuaSource source_;
    /**
     * <pre>
     * For now provide both script and bytecode to support the engine build option
     * of compiling with vanilla lua.
     * </pre>
     *
     * <code>required .dmLuaDDF.LuaSource source = 1;</code>
     * @return Whether the source field is set.
     */
    @java.lang.Override
    public boolean hasSource() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * For now provide both script and bytecode to support the engine build option
     * of compiling with vanilla lua.
     * </pre>
     *
     * <code>required .dmLuaDDF.LuaSource source = 1;</code>
     * @return The source.
     */
    @java.lang.Override
    public com.dynamo.script.proto.Lua.LuaSource getSource() {
      return source_ == null ? com.dynamo.script.proto.Lua.LuaSource.getDefaultInstance() : source_;
    }
    /**
     * <pre>
     * For now provide both script and bytecode to support the engine build option
     * of compiling with vanilla lua.
     * </pre>
     *
     * <code>required .dmLuaDDF.LuaSource source = 1;</code>
     */
    @java.lang.Override
    public com.dynamo.script.proto.Lua.LuaSourceOrBuilder getSourceOrBuilder() {
      return source_ == null ? com.dynamo.script.proto.Lua.LuaSource.getDefaultInstance() : source_;
    }

    public static final int MODULES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList modules_;
    /**
     * <pre>
     * NOTE: The following arrays must be equal in size
     * </pre>
     *
     * <code>repeated string modules = 2;</code>
     * @return A list containing the modules.
     */
    public com.google.protobuf.ProtocolStringList
        getModulesList() {
      return modules_;
    }
    /**
     * <pre>
     * NOTE: The following arrays must be equal in size
     * </pre>
     *
     * <code>repeated string modules = 2;</code>
     * @return The count of modules.
     */
    public int getModulesCount() {
      return modules_.size();
    }
    /**
     * <pre>
     * NOTE: The following arrays must be equal in size
     * </pre>
     *
     * <code>repeated string modules = 2;</code>
     * @param index The index of the element to return.
     * @return The modules at the given index.
     */
    public java.lang.String getModules(int index) {
      return modules_.get(index);
    }
    /**
     * <pre>
     * NOTE: The following arrays must be equal in size
     * </pre>
     *
     * <code>repeated string modules = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the modules at the given index.
     */
    public com.google.protobuf.ByteString
        getModulesBytes(int index) {
      return modules_.getByteString(index);
    }

    public static final int RESOURCES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList resources_;
    /**
     * <pre>
     * required resources. same as modules but on the form /x/y/z.luac instead of x.y.z
     * </pre>
     *
     * <code>repeated string resources = 3 [(.resource) = true];</code>
     * @return A list containing the resources.
     */
    public com.google.protobuf.ProtocolStringList
        getResourcesList() {
      return resources_;
    }
    /**
     * <pre>
     * required resources. same as modules but on the form /x/y/z.luac instead of x.y.z
     * </pre>
     *
     * <code>repeated string resources = 3 [(.resource) = true];</code>
     * @return The count of resources.
     */
    public int getResourcesCount() {
      return resources_.size();
    }
    /**
     * <pre>
     * required resources. same as modules but on the form /x/y/z.luac instead of x.y.z
     * </pre>
     *
     * <code>repeated string resources = 3 [(.resource) = true];</code>
     * @param index The index of the element to return.
     * @return The resources at the given index.
     */
    public java.lang.String getResources(int index) {
      return resources_.get(index);
    }
    /**
     * <pre>
     * required resources. same as modules but on the form /x/y/z.luac instead of x.y.z
     * </pre>
     *
     * <code>repeated string resources = 3 [(.resource) = true];</code>
     * @param index The index of the value to return.
     * @return The bytes of the resources at the given index.
     */
    public com.google.protobuf.ByteString
        getResourcesBytes(int index) {
      return resources_.getByteString(index);
    }

    public static final int PROPERTIES_FIELD_NUMBER = 4;
    private com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations properties_;
    /**
     * <code>optional .dmPropertiesDDF.PropertyDeclarations properties = 4;</code>
     * @return Whether the properties field is set.
     */
    @java.lang.Override
    public boolean hasProperties() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .dmPropertiesDDF.PropertyDeclarations properties = 4;</code>
     * @return The properties.
     */
    @java.lang.Override
    public com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations getProperties() {
      return properties_ == null ? com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations.getDefaultInstance() : properties_;
    }
    /**
     * <code>optional .dmPropertiesDDF.PropertyDeclarations properties = 4;</code>
     */
    @java.lang.Override
    public com.dynamo.properties.proto.PropertiesProto.PropertyDeclarationsOrBuilder getPropertiesOrBuilder() {
      return properties_ == null ? com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations.getDefaultInstance() : properties_;
    }

    public static final int PROPERTY_RESOURCES_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList propertyResources_;
    /**
     * <code>repeated string property_resources = 5 [(.resource) = true];</code>
     * @return A list containing the propertyResources.
     */
    public com.google.protobuf.ProtocolStringList
        getPropertyResourcesList() {
      return propertyResources_;
    }
    /**
     * <code>repeated string property_resources = 5 [(.resource) = true];</code>
     * @return The count of propertyResources.
     */
    public int getPropertyResourcesCount() {
      return propertyResources_.size();
    }
    /**
     * <code>repeated string property_resources = 5 [(.resource) = true];</code>
     * @param index The index of the element to return.
     * @return The propertyResources at the given index.
     */
    public java.lang.String getPropertyResources(int index) {
      return propertyResources_.get(index);
    }
    /**
     * <code>repeated string property_resources = 5 [(.resource) = true];</code>
     * @param index The index of the value to return.
     * @return The bytes of the propertyResources at the given index.
     */
    public com.google.protobuf.ByteString
        getPropertyResourcesBytes(int index) {
      return propertyResources_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSource().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasProperties()) {
        if (!getProperties().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getSource());
      }
      for (int i = 0; i < modules_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, modules_.getRaw(i));
      }
      for (int i = 0; i < resources_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, resources_.getRaw(i));
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(4, getProperties());
      }
      for (int i = 0; i < propertyResources_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, propertyResources_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSource());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < modules_.size(); i++) {
          dataSize += computeStringSizeNoTag(modules_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getModulesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < resources_.size(); i++) {
          dataSize += computeStringSizeNoTag(resources_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getResourcesList().size();
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getProperties());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < propertyResources_.size(); i++) {
          dataSize += computeStringSizeNoTag(propertyResources_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPropertyResourcesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dynamo.lua.proto.Lua.LuaModule)) {
        return super.equals(obj);
      }
      com.dynamo.lua.proto.Lua.LuaModule other = (com.dynamo.lua.proto.Lua.LuaModule) obj;

      if (hasSource() != other.hasSource()) return false;
      if (hasSource()) {
        if (!getSource()
            .equals(other.getSource())) return false;
      }
      if (!getModulesList()
          .equals(other.getModulesList())) return false;
      if (!getResourcesList()
          .equals(other.getResourcesList())) return false;
      if (hasProperties() != other.hasProperties()) return false;
      if (hasProperties()) {
        if (!getProperties()
            .equals(other.getProperties())) return false;
      }
      if (!getPropertyResourcesList()
          .equals(other.getPropertyResourcesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSource()) {
        hash = (37 * hash) + SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getSource().hashCode();
      }
      if (getModulesCount() > 0) {
        hash = (37 * hash) + MODULES_FIELD_NUMBER;
        hash = (53 * hash) + getModulesList().hashCode();
      }
      if (getResourcesCount() > 0) {
        hash = (37 * hash) + RESOURCES_FIELD_NUMBER;
        hash = (53 * hash) + getResourcesList().hashCode();
      }
      if (hasProperties()) {
        hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
        hash = (53 * hash) + getProperties().hashCode();
      }
      if (getPropertyResourcesCount() > 0) {
        hash = (37 * hash) + PROPERTY_RESOURCES_FIELD_NUMBER;
        hash = (53 * hash) + getPropertyResourcesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dynamo.lua.proto.Lua.LuaModule parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dynamo.lua.proto.Lua.LuaModule parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dynamo.lua.proto.Lua.LuaModule parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dynamo.lua.proto.Lua.LuaModule parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dynamo.lua.proto.Lua.LuaModule parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dynamo.lua.proto.Lua.LuaModule parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dynamo.lua.proto.Lua.LuaModule parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dynamo.lua.proto.Lua.LuaModule parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dynamo.lua.proto.Lua.LuaModule parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dynamo.lua.proto.Lua.LuaModule parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dynamo.lua.proto.Lua.LuaModule parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dynamo.lua.proto.Lua.LuaModule parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dynamo.lua.proto.Lua.LuaModule prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dmLuaDDF.LuaModule}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dmLuaDDF.LuaModule)
        com.dynamo.lua.proto.Lua.LuaModuleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dynamo.lua.proto.Lua.internal_static_dmLuaDDF_LuaModule_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dynamo.lua.proto.Lua.internal_static_dmLuaDDF_LuaModule_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dynamo.lua.proto.Lua.LuaModule.class, com.dynamo.lua.proto.Lua.LuaModule.Builder.class);
      }

      // Construct using com.dynamo.lua.proto.Lua.LuaModule.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSourceFieldBuilder();
          getPropertiesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (sourceBuilder_ == null) {
          source_ = null;
        } else {
          sourceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        modules_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        resources_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (propertiesBuilder_ == null) {
          properties_ = null;
        } else {
          propertiesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        propertyResources_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dynamo.lua.proto.Lua.internal_static_dmLuaDDF_LuaModule_descriptor;
      }

      @java.lang.Override
      public com.dynamo.lua.proto.Lua.LuaModule getDefaultInstanceForType() {
        return com.dynamo.lua.proto.Lua.LuaModule.getDefaultInstance();
      }

      @java.lang.Override
      public com.dynamo.lua.proto.Lua.LuaModule build() {
        com.dynamo.lua.proto.Lua.LuaModule result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dynamo.lua.proto.Lua.LuaModule buildPartial() {
        com.dynamo.lua.proto.Lua.LuaModule result = new com.dynamo.lua.proto.Lua.LuaModule(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (sourceBuilder_ == null) {
            result.source_ = source_;
          } else {
            result.source_ = sourceBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          modules_ = modules_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.modules_ = modules_;
        if (((bitField0_ & 0x00000004) != 0)) {
          resources_ = resources_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.resources_ = resources_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          if (propertiesBuilder_ == null) {
            result.properties_ = properties_;
          } else {
            result.properties_ = propertiesBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        if (((bitField0_ & 0x00000010) != 0)) {
          propertyResources_ = propertyResources_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.propertyResources_ = propertyResources_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dynamo.lua.proto.Lua.LuaModule) {
          return mergeFrom((com.dynamo.lua.proto.Lua.LuaModule)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dynamo.lua.proto.Lua.LuaModule other) {
        if (other == com.dynamo.lua.proto.Lua.LuaModule.getDefaultInstance()) return this;
        if (other.hasSource()) {
          mergeSource(other.getSource());
        }
        if (!other.modules_.isEmpty()) {
          if (modules_.isEmpty()) {
            modules_ = other.modules_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureModulesIsMutable();
            modules_.addAll(other.modules_);
          }
          onChanged();
        }
        if (!other.resources_.isEmpty()) {
          if (resources_.isEmpty()) {
            resources_ = other.resources_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureResourcesIsMutable();
            resources_.addAll(other.resources_);
          }
          onChanged();
        }
        if (other.hasProperties()) {
          mergeProperties(other.getProperties());
        }
        if (!other.propertyResources_.isEmpty()) {
          if (propertyResources_.isEmpty()) {
            propertyResources_ = other.propertyResources_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensurePropertyResourcesIsMutable();
            propertyResources_.addAll(other.propertyResources_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSource()) {
          return false;
        }
        if (!getSource().isInitialized()) {
          return false;
        }
        if (hasProperties()) {
          if (!getProperties().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dynamo.lua.proto.Lua.LuaModule parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dynamo.lua.proto.Lua.LuaModule) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.dynamo.script.proto.Lua.LuaSource source_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dynamo.script.proto.Lua.LuaSource, com.dynamo.script.proto.Lua.LuaSource.Builder, com.dynamo.script.proto.Lua.LuaSourceOrBuilder> sourceBuilder_;
      /**
       * <pre>
       * For now provide both script and bytecode to support the engine build option
       * of compiling with vanilla lua.
       * </pre>
       *
       * <code>required .dmLuaDDF.LuaSource source = 1;</code>
       * @return Whether the source field is set.
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * For now provide both script and bytecode to support the engine build option
       * of compiling with vanilla lua.
       * </pre>
       *
       * <code>required .dmLuaDDF.LuaSource source = 1;</code>
       * @return The source.
       */
      public com.dynamo.script.proto.Lua.LuaSource getSource() {
        if (sourceBuilder_ == null) {
          return source_ == null ? com.dynamo.script.proto.Lua.LuaSource.getDefaultInstance() : source_;
        } else {
          return sourceBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * For now provide both script and bytecode to support the engine build option
       * of compiling with vanilla lua.
       * </pre>
       *
       * <code>required .dmLuaDDF.LuaSource source = 1;</code>
       */
      public Builder setSource(com.dynamo.script.proto.Lua.LuaSource value) {
        if (sourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          source_ = value;
          onChanged();
        } else {
          sourceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * For now provide both script and bytecode to support the engine build option
       * of compiling with vanilla lua.
       * </pre>
       *
       * <code>required .dmLuaDDF.LuaSource source = 1;</code>
       */
      public Builder setSource(
          com.dynamo.script.proto.Lua.LuaSource.Builder builderForValue) {
        if (sourceBuilder_ == null) {
          source_ = builderForValue.build();
          onChanged();
        } else {
          sourceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * For now provide both script and bytecode to support the engine build option
       * of compiling with vanilla lua.
       * </pre>
       *
       * <code>required .dmLuaDDF.LuaSource source = 1;</code>
       */
      public Builder mergeSource(com.dynamo.script.proto.Lua.LuaSource value) {
        if (sourceBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              source_ != null &&
              source_ != com.dynamo.script.proto.Lua.LuaSource.getDefaultInstance()) {
            source_ =
              com.dynamo.script.proto.Lua.LuaSource.newBuilder(source_).mergeFrom(value).buildPartial();
          } else {
            source_ = value;
          }
          onChanged();
        } else {
          sourceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * For now provide both script and bytecode to support the engine build option
       * of compiling with vanilla lua.
       * </pre>
       *
       * <code>required .dmLuaDDF.LuaSource source = 1;</code>
       */
      public Builder clearSource() {
        if (sourceBuilder_ == null) {
          source_ = null;
          onChanged();
        } else {
          sourceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       * For now provide both script and bytecode to support the engine build option
       * of compiling with vanilla lua.
       * </pre>
       *
       * <code>required .dmLuaDDF.LuaSource source = 1;</code>
       */
      public com.dynamo.script.proto.Lua.LuaSource.Builder getSourceBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSourceFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * For now provide both script and bytecode to support the engine build option
       * of compiling with vanilla lua.
       * </pre>
       *
       * <code>required .dmLuaDDF.LuaSource source = 1;</code>
       */
      public com.dynamo.script.proto.Lua.LuaSourceOrBuilder getSourceOrBuilder() {
        if (sourceBuilder_ != null) {
          return sourceBuilder_.getMessageOrBuilder();
        } else {
          return source_ == null ?
              com.dynamo.script.proto.Lua.LuaSource.getDefaultInstance() : source_;
        }
      }
      /**
       * <pre>
       * For now provide both script and bytecode to support the engine build option
       * of compiling with vanilla lua.
       * </pre>
       *
       * <code>required .dmLuaDDF.LuaSource source = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dynamo.script.proto.Lua.LuaSource, com.dynamo.script.proto.Lua.LuaSource.Builder, com.dynamo.script.proto.Lua.LuaSourceOrBuilder> 
          getSourceFieldBuilder() {
        if (sourceBuilder_ == null) {
          sourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.dynamo.script.proto.Lua.LuaSource, com.dynamo.script.proto.Lua.LuaSource.Builder, com.dynamo.script.proto.Lua.LuaSourceOrBuilder>(
                  getSource(),
                  getParentForChildren(),
                  isClean());
          source_ = null;
        }
        return sourceBuilder_;
      }

      private com.google.protobuf.LazyStringList modules_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureModulesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          modules_ = new com.google.protobuf.LazyStringArrayList(modules_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       * NOTE: The following arrays must be equal in size
       * </pre>
       *
       * <code>repeated string modules = 2;</code>
       * @return A list containing the modules.
       */
      public com.google.protobuf.ProtocolStringList
          getModulesList() {
        return modules_.getUnmodifiableView();
      }
      /**
       * <pre>
       * NOTE: The following arrays must be equal in size
       * </pre>
       *
       * <code>repeated string modules = 2;</code>
       * @return The count of modules.
       */
      public int getModulesCount() {
        return modules_.size();
      }
      /**
       * <pre>
       * NOTE: The following arrays must be equal in size
       * </pre>
       *
       * <code>repeated string modules = 2;</code>
       * @param index The index of the element to return.
       * @return The modules at the given index.
       */
      public java.lang.String getModules(int index) {
        return modules_.get(index);
      }
      /**
       * <pre>
       * NOTE: The following arrays must be equal in size
       * </pre>
       *
       * <code>repeated string modules = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the modules at the given index.
       */
      public com.google.protobuf.ByteString
          getModulesBytes(int index) {
        return modules_.getByteString(index);
      }
      /**
       * <pre>
       * NOTE: The following arrays must be equal in size
       * </pre>
       *
       * <code>repeated string modules = 2;</code>
       * @param index The index to set the value at.
       * @param value The modules to set.
       * @return This builder for chaining.
       */
      public Builder setModules(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureModulesIsMutable();
        modules_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * NOTE: The following arrays must be equal in size
       * </pre>
       *
       * <code>repeated string modules = 2;</code>
       * @param value The modules to add.
       * @return This builder for chaining.
       */
      public Builder addModules(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureModulesIsMutable();
        modules_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * NOTE: The following arrays must be equal in size
       * </pre>
       *
       * <code>repeated string modules = 2;</code>
       * @param values The modules to add.
       * @return This builder for chaining.
       */
      public Builder addAllModules(
          java.lang.Iterable<java.lang.String> values) {
        ensureModulesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, modules_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * NOTE: The following arrays must be equal in size
       * </pre>
       *
       * <code>repeated string modules = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearModules() {
        modules_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * NOTE: The following arrays must be equal in size
       * </pre>
       *
       * <code>repeated string modules = 2;</code>
       * @param value The bytes of the modules to add.
       * @return This builder for chaining.
       */
      public Builder addModulesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureModulesIsMutable();
        modules_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList resources_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureResourcesIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          resources_ = new com.google.protobuf.LazyStringArrayList(resources_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <pre>
       * required resources. same as modules but on the form /x/y/z.luac instead of x.y.z
       * </pre>
       *
       * <code>repeated string resources = 3 [(.resource) = true];</code>
       * @return A list containing the resources.
       */
      public com.google.protobuf.ProtocolStringList
          getResourcesList() {
        return resources_.getUnmodifiableView();
      }
      /**
       * <pre>
       * required resources. same as modules but on the form /x/y/z.luac instead of x.y.z
       * </pre>
       *
       * <code>repeated string resources = 3 [(.resource) = true];</code>
       * @return The count of resources.
       */
      public int getResourcesCount() {
        return resources_.size();
      }
      /**
       * <pre>
       * required resources. same as modules but on the form /x/y/z.luac instead of x.y.z
       * </pre>
       *
       * <code>repeated string resources = 3 [(.resource) = true];</code>
       * @param index The index of the element to return.
       * @return The resources at the given index.
       */
      public java.lang.String getResources(int index) {
        return resources_.get(index);
      }
      /**
       * <pre>
       * required resources. same as modules but on the form /x/y/z.luac instead of x.y.z
       * </pre>
       *
       * <code>repeated string resources = 3 [(.resource) = true];</code>
       * @param index The index of the value to return.
       * @return The bytes of the resources at the given index.
       */
      public com.google.protobuf.ByteString
          getResourcesBytes(int index) {
        return resources_.getByteString(index);
      }
      /**
       * <pre>
       * required resources. same as modules but on the form /x/y/z.luac instead of x.y.z
       * </pre>
       *
       * <code>repeated string resources = 3 [(.resource) = true];</code>
       * @param index The index to set the value at.
       * @param value The resources to set.
       * @return This builder for chaining.
       */
      public Builder setResources(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureResourcesIsMutable();
        resources_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * required resources. same as modules but on the form /x/y/z.luac instead of x.y.z
       * </pre>
       *
       * <code>repeated string resources = 3 [(.resource) = true];</code>
       * @param value The resources to add.
       * @return This builder for chaining.
       */
      public Builder addResources(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureResourcesIsMutable();
        resources_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * required resources. same as modules but on the form /x/y/z.luac instead of x.y.z
       * </pre>
       *
       * <code>repeated string resources = 3 [(.resource) = true];</code>
       * @param values The resources to add.
       * @return This builder for chaining.
       */
      public Builder addAllResources(
          java.lang.Iterable<java.lang.String> values) {
        ensureResourcesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, resources_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * required resources. same as modules but on the form /x/y/z.luac instead of x.y.z
       * </pre>
       *
       * <code>repeated string resources = 3 [(.resource) = true];</code>
       * @return This builder for chaining.
       */
      public Builder clearResources() {
        resources_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * required resources. same as modules but on the form /x/y/z.luac instead of x.y.z
       * </pre>
       *
       * <code>repeated string resources = 3 [(.resource) = true];</code>
       * @param value The bytes of the resources to add.
       * @return This builder for chaining.
       */
      public Builder addResourcesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureResourcesIsMutable();
        resources_.add(value);
        onChanged();
        return this;
      }

      private com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations properties_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations, com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations.Builder, com.dynamo.properties.proto.PropertiesProto.PropertyDeclarationsOrBuilder> propertiesBuilder_;
      /**
       * <code>optional .dmPropertiesDDF.PropertyDeclarations properties = 4;</code>
       * @return Whether the properties field is set.
       */
      public boolean hasProperties() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional .dmPropertiesDDF.PropertyDeclarations properties = 4;</code>
       * @return The properties.
       */
      public com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations getProperties() {
        if (propertiesBuilder_ == null) {
          return properties_ == null ? com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations.getDefaultInstance() : properties_;
        } else {
          return propertiesBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .dmPropertiesDDF.PropertyDeclarations properties = 4;</code>
       */
      public Builder setProperties(com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations value) {
        if (propertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          properties_ = value;
          onChanged();
        } else {
          propertiesBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .dmPropertiesDDF.PropertyDeclarations properties = 4;</code>
       */
      public Builder setProperties(
          com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations.Builder builderForValue) {
        if (propertiesBuilder_ == null) {
          properties_ = builderForValue.build();
          onChanged();
        } else {
          propertiesBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .dmPropertiesDDF.PropertyDeclarations properties = 4;</code>
       */
      public Builder mergeProperties(com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations value) {
        if (propertiesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
              properties_ != null &&
              properties_ != com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations.getDefaultInstance()) {
            properties_ =
              com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations.newBuilder(properties_).mergeFrom(value).buildPartial();
          } else {
            properties_ = value;
          }
          onChanged();
        } else {
          propertiesBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .dmPropertiesDDF.PropertyDeclarations properties = 4;</code>
       */
      public Builder clearProperties() {
        if (propertiesBuilder_ == null) {
          properties_ = null;
          onChanged();
        } else {
          propertiesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .dmPropertiesDDF.PropertyDeclarations properties = 4;</code>
       */
      public com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations.Builder getPropertiesBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getPropertiesFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .dmPropertiesDDF.PropertyDeclarations properties = 4;</code>
       */
      public com.dynamo.properties.proto.PropertiesProto.PropertyDeclarationsOrBuilder getPropertiesOrBuilder() {
        if (propertiesBuilder_ != null) {
          return propertiesBuilder_.getMessageOrBuilder();
        } else {
          return properties_ == null ?
              com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations.getDefaultInstance() : properties_;
        }
      }
      /**
       * <code>optional .dmPropertiesDDF.PropertyDeclarations properties = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations, com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations.Builder, com.dynamo.properties.proto.PropertiesProto.PropertyDeclarationsOrBuilder> 
          getPropertiesFieldBuilder() {
        if (propertiesBuilder_ == null) {
          propertiesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations, com.dynamo.properties.proto.PropertiesProto.PropertyDeclarations.Builder, com.dynamo.properties.proto.PropertiesProto.PropertyDeclarationsOrBuilder>(
                  getProperties(),
                  getParentForChildren(),
                  isClean());
          properties_ = null;
        }
        return propertiesBuilder_;
      }

      private com.google.protobuf.LazyStringList propertyResources_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePropertyResourcesIsMutable() {
        if (!((bitField0_ & 0x00000010) != 0)) {
          propertyResources_ = new com.google.protobuf.LazyStringArrayList(propertyResources_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string property_resources = 5 [(.resource) = true];</code>
       * @return A list containing the propertyResources.
       */
      public com.google.protobuf.ProtocolStringList
          getPropertyResourcesList() {
        return propertyResources_.getUnmodifiableView();
      }
      /**
       * <code>repeated string property_resources = 5 [(.resource) = true];</code>
       * @return The count of propertyResources.
       */
      public int getPropertyResourcesCount() {
        return propertyResources_.size();
      }
      /**
       * <code>repeated string property_resources = 5 [(.resource) = true];</code>
       * @param index The index of the element to return.
       * @return The propertyResources at the given index.
       */
      public java.lang.String getPropertyResources(int index) {
        return propertyResources_.get(index);
      }
      /**
       * <code>repeated string property_resources = 5 [(.resource) = true];</code>
       * @param index The index of the value to return.
       * @return The bytes of the propertyResources at the given index.
       */
      public com.google.protobuf.ByteString
          getPropertyResourcesBytes(int index) {
        return propertyResources_.getByteString(index);
      }
      /**
       * <code>repeated string property_resources = 5 [(.resource) = true];</code>
       * @param index The index to set the value at.
       * @param value The propertyResources to set.
       * @return This builder for chaining.
       */
      public Builder setPropertyResources(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePropertyResourcesIsMutable();
        propertyResources_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string property_resources = 5 [(.resource) = true];</code>
       * @param value The propertyResources to add.
       * @return This builder for chaining.
       */
      public Builder addPropertyResources(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePropertyResourcesIsMutable();
        propertyResources_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string property_resources = 5 [(.resource) = true];</code>
       * @param values The propertyResources to add.
       * @return This builder for chaining.
       */
      public Builder addAllPropertyResources(
          java.lang.Iterable<java.lang.String> values) {
        ensurePropertyResourcesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, propertyResources_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string property_resources = 5 [(.resource) = true];</code>
       * @return This builder for chaining.
       */
      public Builder clearPropertyResources() {
        propertyResources_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string property_resources = 5 [(.resource) = true];</code>
       * @param value The bytes of the propertyResources to add.
       * @return This builder for chaining.
       */
      public Builder addPropertyResourcesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePropertyResourcesIsMutable();
        propertyResources_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dmLuaDDF.LuaModule)
    }

    // @@protoc_insertion_point(class_scope:dmLuaDDF.LuaModule)
    private static final com.dynamo.lua.proto.Lua.LuaModule DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dynamo.lua.proto.Lua.LuaModule();
    }

    public static com.dynamo.lua.proto.Lua.LuaModule getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LuaModule>
        PARSER = new com.google.protobuf.AbstractParser<LuaModule>() {
      @java.lang.Override
      public LuaModule parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LuaModule(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LuaModule> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LuaModule> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dynamo.lua.proto.Lua.LuaModule getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dmLuaDDF_LuaModule_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dmLuaDDF_LuaModule_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0engine/gameobject/proto/gameobject/lua" +
      "_ddf.proto\022\010dmLuaDDF\032\030ddf/ddf_extensions" +
      ".proto\032\022ddf/ddf_math.proto\032\033script/lua_s" +
      "ource_ddf.proto\032\037gameobject/properties_d" +
      "df.proto\"\267\001\n\tLuaModule\022#\n\006source\030\001 \002(\0132\023" +
      ".dmLuaDDF.LuaSource\022\017\n\007modules\030\002 \003(\t\022\027\n\t" +
      "resources\030\003 \003(\tB\004\240\273\030\001\0229\n\nproperties\030\004 \001(" +
      "\0132%.dmPropertiesDDF.PropertyDeclarations" +
      "\022 \n\022property_resources\030\005 \003(\tB\004\240\273\030\001B\033\n\024co" +
      "m.dynamo.lua.protoB\003Lua"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dynamo.proto.DdfExtensions.getDescriptor(),
          com.dynamo.proto.DdfMath.getDescriptor(),
          com.dynamo.script.proto.Lua.getDescriptor(),
          com.dynamo.properties.proto.PropertiesProto.getDescriptor(),
        });
    internal_static_dmLuaDDF_LuaModule_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dmLuaDDF_LuaModule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dmLuaDDF_LuaModule_descriptor,
        new java.lang.String[] { "Source", "Modules", "Resources", "Properties", "PropertyResources", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.dynamo.proto.DdfExtensions.resource);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.dynamo.proto.DdfExtensions.getDescriptor();
    com.dynamo.proto.DdfMath.getDescriptor();
    com.dynamo.script.proto.Lua.getDescriptor();
    com.dynamo.properties.proto.PropertiesProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
