// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: engine/script/src/script/lua_source_ddf.proto

package com.dynamo.script.proto;

public final class Lua {
  private Lua() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LuaSourceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dmLuaDDF.LuaSource)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * HTML platforms uses script (vanilla lua), all
     * other platforms uses bytecode instead.
     * </pre>
     *
     * <code>optional bytes script = 1;</code>
     * @return Whether the script field is set.
     */
    boolean hasScript();
    /**
     * <pre>
     * HTML platforms uses script (vanilla lua), all
     * other platforms uses bytecode instead.
     * </pre>
     *
     * <code>optional bytes script = 1;</code>
     * @return The script.
     */
    com.google.protobuf.ByteString getScript();

    /**
     * <pre>
     * Path to the original file; used for debugging.
     * Note that if bytecode is supplied from LuaJIT it will contain embedded
     * chunk names that override this file name and this field is not used.
     * </pre>
     *
     * <code>required string filename = 2;</code>
     * @return Whether the filename field is set.
     */
    boolean hasFilename();
    /**
     * <pre>
     * Path to the original file; used for debugging.
     * Note that if bytecode is supplied from LuaJIT it will contain embedded
     * chunk names that override this file name and this field is not used.
     * </pre>
     *
     * <code>required string filename = 2;</code>
     * @return The filename.
     */
    java.lang.String getFilename();
    /**
     * <pre>
     * Path to the original file; used for debugging.
     * Note that if bytecode is supplied from LuaJIT it will contain embedded
     * chunk names that override this file name and this field is not used.
     * </pre>
     *
     * <code>required string filename = 2;</code>
     * @return The bytes for filename.
     */
    com.google.protobuf.ByteString
        getFilenameBytes();

    /**
     * <code>optional bytes bytecode = 3;</code>
     * @return Whether the bytecode field is set.
     */
    boolean hasBytecode();
    /**
     * <code>optional bytes bytecode = 3;</code>
     * @return The bytecode.
     */
    com.google.protobuf.ByteString getBytecode();

    /**
     * <code>optional bytes bytecode_64 = 4;</code>
     * @return Whether the bytecode64 field is set.
     */
    boolean hasBytecode64();
    /**
     * <code>optional bytes bytecode_64 = 4;</code>
     * @return The bytecode64.
     */
    com.google.protobuf.ByteString getBytecode64();

    /**
     * <code>optional bytes delta = 5;</code>
     * @return Whether the delta field is set.
     */
    boolean hasDelta();
    /**
     * <code>optional bytes delta = 5;</code>
     * @return The delta.
     */
    com.google.protobuf.ByteString getDelta();
  }
  /**
   * Protobuf type {@code dmLuaDDF.LuaSource}
   */
  public static final class LuaSource extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dmLuaDDF.LuaSource)
      LuaSourceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LuaSource.newBuilder() to construct.
    private LuaSource(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LuaSource() {
      script_ = com.google.protobuf.ByteString.EMPTY;
      filename_ = "";
      bytecode_ = com.google.protobuf.ByteString.EMPTY;
      bytecode64_ = com.google.protobuf.ByteString.EMPTY;
      delta_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LuaSource();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LuaSource(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              script_ = input.readBytes();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              filename_ = bs;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              bytecode_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              bytecode64_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              delta_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dynamo.script.proto.Lua.internal_static_dmLuaDDF_LuaSource_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dynamo.script.proto.Lua.internal_static_dmLuaDDF_LuaSource_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dynamo.script.proto.Lua.LuaSource.class, com.dynamo.script.proto.Lua.LuaSource.Builder.class);
    }

    private int bitField0_;
    public static final int SCRIPT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString script_;
    /**
     * <pre>
     * HTML platforms uses script (vanilla lua), all
     * other platforms uses bytecode instead.
     * </pre>
     *
     * <code>optional bytes script = 1;</code>
     * @return Whether the script field is set.
     */
    @java.lang.Override
    public boolean hasScript() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * HTML platforms uses script (vanilla lua), all
     * other platforms uses bytecode instead.
     * </pre>
     *
     * <code>optional bytes script = 1;</code>
     * @return The script.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getScript() {
      return script_;
    }

    public static final int FILENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object filename_;
    /**
     * <pre>
     * Path to the original file; used for debugging.
     * Note that if bytecode is supplied from LuaJIT it will contain embedded
     * chunk names that override this file name and this field is not used.
     * </pre>
     *
     * <code>required string filename = 2;</code>
     * @return Whether the filename field is set.
     */
    @java.lang.Override
    public boolean hasFilename() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Path to the original file; used for debugging.
     * Note that if bytecode is supplied from LuaJIT it will contain embedded
     * chunk names that override this file name and this field is not used.
     * </pre>
     *
     * <code>required string filename = 2;</code>
     * @return The filename.
     */
    @java.lang.Override
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filename_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Path to the original file; used for debugging.
     * Note that if bytecode is supplied from LuaJIT it will contain embedded
     * chunk names that override this file name and this field is not used.
     * </pre>
     *
     * <code>required string filename = 2;</code>
     * @return The bytes for filename.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BYTECODE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString bytecode_;
    /**
     * <code>optional bytes bytecode = 3;</code>
     * @return Whether the bytecode field is set.
     */
    @java.lang.Override
    public boolean hasBytecode() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes bytecode = 3;</code>
     * @return The bytecode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytecode() {
      return bytecode_;
    }

    public static final int BYTECODE_64_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString bytecode64_;
    /**
     * <code>optional bytes bytecode_64 = 4;</code>
     * @return Whether the bytecode64 field is set.
     */
    @java.lang.Override
    public boolean hasBytecode64() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes bytecode_64 = 4;</code>
     * @return The bytecode64.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBytecode64() {
      return bytecode64_;
    }

    public static final int DELTA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString delta_;
    /**
     * <code>optional bytes delta = 5;</code>
     * @return Whether the delta field is set.
     */
    @java.lang.Override
    public boolean hasDelta() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional bytes delta = 5;</code>
     * @return The delta.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDelta() {
      return delta_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFilename()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, script_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, filename_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(3, bytecode_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, bytecode64_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBytes(5, delta_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, script_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, filename_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, bytecode_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, bytecode64_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, delta_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dynamo.script.proto.Lua.LuaSource)) {
        return super.equals(obj);
      }
      com.dynamo.script.proto.Lua.LuaSource other = (com.dynamo.script.proto.Lua.LuaSource) obj;

      if (hasScript() != other.hasScript()) return false;
      if (hasScript()) {
        if (!getScript()
            .equals(other.getScript())) return false;
      }
      if (hasFilename() != other.hasFilename()) return false;
      if (hasFilename()) {
        if (!getFilename()
            .equals(other.getFilename())) return false;
      }
      if (hasBytecode() != other.hasBytecode()) return false;
      if (hasBytecode()) {
        if (!getBytecode()
            .equals(other.getBytecode())) return false;
      }
      if (hasBytecode64() != other.hasBytecode64()) return false;
      if (hasBytecode64()) {
        if (!getBytecode64()
            .equals(other.getBytecode64())) return false;
      }
      if (hasDelta() != other.hasDelta()) return false;
      if (hasDelta()) {
        if (!getDelta()
            .equals(other.getDelta())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasScript()) {
        hash = (37 * hash) + SCRIPT_FIELD_NUMBER;
        hash = (53 * hash) + getScript().hashCode();
      }
      if (hasFilename()) {
        hash = (37 * hash) + FILENAME_FIELD_NUMBER;
        hash = (53 * hash) + getFilename().hashCode();
      }
      if (hasBytecode()) {
        hash = (37 * hash) + BYTECODE_FIELD_NUMBER;
        hash = (53 * hash) + getBytecode().hashCode();
      }
      if (hasBytecode64()) {
        hash = (37 * hash) + BYTECODE_64_FIELD_NUMBER;
        hash = (53 * hash) + getBytecode64().hashCode();
      }
      if (hasDelta()) {
        hash = (37 * hash) + DELTA_FIELD_NUMBER;
        hash = (53 * hash) + getDelta().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dynamo.script.proto.Lua.LuaSource parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dynamo.script.proto.Lua.LuaSource parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dynamo.script.proto.Lua.LuaSource parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dynamo.script.proto.Lua.LuaSource parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dynamo.script.proto.Lua.LuaSource parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dynamo.script.proto.Lua.LuaSource parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dynamo.script.proto.Lua.LuaSource parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dynamo.script.proto.Lua.LuaSource parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dynamo.script.proto.Lua.LuaSource parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dynamo.script.proto.Lua.LuaSource parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dynamo.script.proto.Lua.LuaSource parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dynamo.script.proto.Lua.LuaSource parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dynamo.script.proto.Lua.LuaSource prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dmLuaDDF.LuaSource}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dmLuaDDF.LuaSource)
        com.dynamo.script.proto.Lua.LuaSourceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dynamo.script.proto.Lua.internal_static_dmLuaDDF_LuaSource_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dynamo.script.proto.Lua.internal_static_dmLuaDDF_LuaSource_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dynamo.script.proto.Lua.LuaSource.class, com.dynamo.script.proto.Lua.LuaSource.Builder.class);
      }

      // Construct using com.dynamo.script.proto.Lua.LuaSource.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        script_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        filename_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        bytecode_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        bytecode64_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        delta_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dynamo.script.proto.Lua.internal_static_dmLuaDDF_LuaSource_descriptor;
      }

      @java.lang.Override
      public com.dynamo.script.proto.Lua.LuaSource getDefaultInstanceForType() {
        return com.dynamo.script.proto.Lua.LuaSource.getDefaultInstance();
      }

      @java.lang.Override
      public com.dynamo.script.proto.Lua.LuaSource build() {
        com.dynamo.script.proto.Lua.LuaSource result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dynamo.script.proto.Lua.LuaSource buildPartial() {
        com.dynamo.script.proto.Lua.LuaSource result = new com.dynamo.script.proto.Lua.LuaSource(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.script_ = script_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.filename_ = filename_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.bytecode_ = bytecode_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.bytecode64_ = bytecode64_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.delta_ = delta_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dynamo.script.proto.Lua.LuaSource) {
          return mergeFrom((com.dynamo.script.proto.Lua.LuaSource)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dynamo.script.proto.Lua.LuaSource other) {
        if (other == com.dynamo.script.proto.Lua.LuaSource.getDefaultInstance()) return this;
        if (other.hasScript()) {
          setScript(other.getScript());
        }
        if (other.hasFilename()) {
          bitField0_ |= 0x00000002;
          filename_ = other.filename_;
          onChanged();
        }
        if (other.hasBytecode()) {
          setBytecode(other.getBytecode());
        }
        if (other.hasBytecode64()) {
          setBytecode64(other.getBytecode64());
        }
        if (other.hasDelta()) {
          setDelta(other.getDelta());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasFilename()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dynamo.script.proto.Lua.LuaSource parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dynamo.script.proto.Lua.LuaSource) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString script_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * HTML platforms uses script (vanilla lua), all
       * other platforms uses bytecode instead.
       * </pre>
       *
       * <code>optional bytes script = 1;</code>
       * @return Whether the script field is set.
       */
      @java.lang.Override
      public boolean hasScript() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * HTML platforms uses script (vanilla lua), all
       * other platforms uses bytecode instead.
       * </pre>
       *
       * <code>optional bytes script = 1;</code>
       * @return The script.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getScript() {
        return script_;
      }
      /**
       * <pre>
       * HTML platforms uses script (vanilla lua), all
       * other platforms uses bytecode instead.
       * </pre>
       *
       * <code>optional bytes script = 1;</code>
       * @param value The script to set.
       * @return This builder for chaining.
       */
      public Builder setScript(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        script_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * HTML platforms uses script (vanilla lua), all
       * other platforms uses bytecode instead.
       * </pre>
       *
       * <code>optional bytes script = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearScript() {
        bitField0_ = (bitField0_ & ~0x00000001);
        script_ = getDefaultInstance().getScript();
        onChanged();
        return this;
      }

      private java.lang.Object filename_ = "";
      /**
       * <pre>
       * Path to the original file; used for debugging.
       * Note that if bytecode is supplied from LuaJIT it will contain embedded
       * chunk names that override this file name and this field is not used.
       * </pre>
       *
       * <code>required string filename = 2;</code>
       * @return Whether the filename field is set.
       */
      public boolean hasFilename() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Path to the original file; used for debugging.
       * Note that if bytecode is supplied from LuaJIT it will contain embedded
       * chunk names that override this file name and this field is not used.
       * </pre>
       *
       * <code>required string filename = 2;</code>
       * @return The filename.
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            filename_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Path to the original file; used for debugging.
       * Note that if bytecode is supplied from LuaJIT it will contain embedded
       * chunk names that override this file name and this field is not used.
       * </pre>
       *
       * <code>required string filename = 2;</code>
       * @return The bytes for filename.
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Path to the original file; used for debugging.
       * Note that if bytecode is supplied from LuaJIT it will contain embedded
       * chunk names that override this file name and this field is not used.
       * </pre>
       *
       * <code>required string filename = 2;</code>
       * @param value The filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        filename_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Path to the original file; used for debugging.
       * Note that if bytecode is supplied from LuaJIT it will contain embedded
       * chunk names that override this file name and this field is not used.
       * </pre>
       *
       * <code>required string filename = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilename() {
        bitField0_ = (bitField0_ & ~0x00000002);
        filename_ = getDefaultInstance().getFilename();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Path to the original file; used for debugging.
       * Note that if bytecode is supplied from LuaJIT it will contain embedded
       * chunk names that override this file name and this field is not used.
       * </pre>
       *
       * <code>required string filename = 2;</code>
       * @param value The bytes for filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        filename_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytecode_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes bytecode = 3;</code>
       * @return Whether the bytecode field is set.
       */
      @java.lang.Override
      public boolean hasBytecode() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional bytes bytecode = 3;</code>
       * @return The bytecode.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBytecode() {
        return bytecode_;
      }
      /**
       * <code>optional bytes bytecode = 3;</code>
       * @param value The bytecode to set.
       * @return This builder for chaining.
       */
      public Builder setBytecode(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        bytecode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes bytecode = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBytecode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        bytecode_ = getDefaultInstance().getBytecode();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytecode64_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes bytecode_64 = 4;</code>
       * @return Whether the bytecode64 field is set.
       */
      @java.lang.Override
      public boolean hasBytecode64() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bytes bytecode_64 = 4;</code>
       * @return The bytecode64.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBytecode64() {
        return bytecode64_;
      }
      /**
       * <code>optional bytes bytecode_64 = 4;</code>
       * @param value The bytecode64 to set.
       * @return This builder for chaining.
       */
      public Builder setBytecode64(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        bytecode64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes bytecode_64 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBytecode64() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bytecode64_ = getDefaultInstance().getBytecode64();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString delta_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes delta = 5;</code>
       * @return Whether the delta field is set.
       */
      @java.lang.Override
      public boolean hasDelta() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional bytes delta = 5;</code>
       * @return The delta.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getDelta() {
        return delta_;
      }
      /**
       * <code>optional bytes delta = 5;</code>
       * @param value The delta to set.
       * @return This builder for chaining.
       */
      public Builder setDelta(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        delta_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes delta = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDelta() {
        bitField0_ = (bitField0_ & ~0x00000010);
        delta_ = getDefaultInstance().getDelta();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dmLuaDDF.LuaSource)
    }

    // @@protoc_insertion_point(class_scope:dmLuaDDF.LuaSource)
    private static final com.dynamo.script.proto.Lua.LuaSource DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dynamo.script.proto.Lua.LuaSource();
    }

    public static com.dynamo.script.proto.Lua.LuaSource getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LuaSource>
        PARSER = new com.google.protobuf.AbstractParser<LuaSource>() {
      @java.lang.Override
      public LuaSource parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LuaSource(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LuaSource> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LuaSource> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dynamo.script.proto.Lua.LuaSource getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dmLuaDDF_LuaSource_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dmLuaDDF_LuaSource_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-engine/script/src/script/lua_source_dd" +
      "f.proto\022\010dmLuaDDF\"c\n\tLuaSource\022\016\n\006script" +
      "\030\001 \001(\014\022\020\n\010filename\030\002 \002(\t\022\020\n\010bytecode\030\003 \001" +
      "(\014\022\023\n\013bytecode_64\030\004 \001(\014\022\r\n\005delta\030\005 \001(\014B\036" +
      "\n\027com.dynamo.script.protoB\003Lua"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dmLuaDDF_LuaSource_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dmLuaDDF_LuaSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dmLuaDDF_LuaSource_descriptor,
        new java.lang.String[] { "Script", "Filename", "Bytecode", "Bytecode64", "Delta", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
